import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js';
import { getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js';
import { getFirestore,collection,getDocs,query,orderBy,limit,doc,getDoc,setDoc,addDoc,serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js';

const ADMIN_EMAIL='sandip2007mukherjee@gmail.com';
const firebaseConfig={apiKey:'AIzaSyCrfUkI-ZE1jQ160INFxcUxhUwSiDvZbbk',authDomain:'workshop-c2bd7.firebaseapp.com',projectId:'workshop-c2bd7',storageBucket:'workshop-c2bd7.firebasestorage.app',messagingSenderId:'813904771823',appId:'1:813904771823:web:35c19cf502b6dd8e1a791a'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id);
$('loginBtn').onclick=async()=>{const email=$('email').value.trim().toLowerCase(),password=$('password').value;if(email!==ADMIN_EMAIL){$('loginMsg').textContent='এই email-টি Admin নয়।';return}try{await signInWithEmailAndPassword(auth,email,password)}catch(e){$('loginMsg').textContent='Login failed: '+(e.code||e.message)}};
$('logoutBtn').onclick=()=>signOut(auth);$('refreshBtn').onclick=loadAll;
$('saveSettings').onclick=async()=>{try{await setDoc(doc(db,'settings','main'),{finalMessage:$('finalMessage').value.trim(),animationIntensity:$('intensity').value,updatedAt:serverTimestamp()},{merge:true});$('saveMsg').textContent='Saved ✓'}catch(e){$('saveMsg').textContent=e.message}};
$('addEmotion').onclick=()=>addEmotionRow({emoji:'✨',title:'নতুন অনুভূতি',description:'আজকের অনুভূতি'});
function addEmotionRow(x){const row=document.createElement('div');row.className='emotionRow';row.innerHTML=`<input class="emEmoji" value="${esc(x.emoji||'')}" maxlength="4"><input class="emTitle" value="${esc(x.title||'')}"><button>Save</button>`;row.querySelector('button').onclick=async()=>{try{await addDoc(collection(db,'emotions'),{emoji:row.querySelector('.emEmoji').value,title:row.querySelector('.emTitle').value,description:x.description||'',createdAt:serverTimestamp()});row.remove()}catch(e){alert(e.message)}};$('emotionList').appendChild(row)}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
async function loadSettings(){const s=await getDoc(doc(db,'settings','main'));if(s.exists()){const d=s.data();$('finalMessage').value=d.finalMessage||'';$('intensity').value=d.animationIntensity||'high'}}
async function loadEmotions(){const snap=await getDocs(collection(db,'emotions'));$('emotionList').innerHTML='';snap.forEach(d=>addEmotionRow({emoji:d.data().emoji,title:d.data().title,description:d.data().description,id:d.id}))}
async function loadActivity(){let snap;try{snap=await getDocs(query(collection(db,'activities'),orderBy('createdAt','desc'),limit(100)))}catch(e){snap=await getDocs(collection(db,'activities'))}let users=new Set(),notes=0,finals=0,animations=0;const rows=[];snap.forEach(d=>{const x=d.data();if(x.name)users.add(x.name);const a=x.action||x.type||'';if(/note|view/i.test(a))notes++;if(/final|button|favorite|yes/i.test(a))finals++;if(/animation|heart/i.test(a))animations++;rows.push(x)});$('usersCount').textContent=users.size;$('notesCount').textContent=notes;$('finalCount').textContent=finals;$('animationCount').textContent=animations;$('activityBody').innerHTML=rows.slice(0,50).map(x=>`<tr><td>${esc(x.name||'-')}</td><td>${esc(x.emotionLabel||x.emotion||'-')}</td><td>${esc(x.action||x.type||'-')}</td><td>${formatTime(x.createdAt)}</td></tr>`).join('')||'<tr><td colspan="4">No activity yet.</td></tr>'}
function formatTime(t){if(!t)return'-';try{return t.toDate().toLocaleString('en-IN',{dateStyle:'short',timeStyle:'short'})}catch{return'-'}}
async function loadAll(){await Promise.all([loadSettings(),loadEmotions(),loadActivity()])}
onAuthStateChanged(auth,async user=>{if(user&&user.email?.toLowerCase()===ADMIN_EMAIL){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('adminEmail').textContent=user.email;await loadAll()}else{$('appView').classList.add('hidden');$('loginView').classList.remove('hidden')}});
